image: maven:3.8.6-openjdk-17  # Updated to include Java 17

pipelines:
  default:
    - parallel:
        - step:
            name: Verify
            script:
              - mvn clean install -B  # Runs the build with Maven
            after-script:
              # Collect checkstyle results, if any, and convert to Bitbucket Code Insights.
              - pipe: atlassian/checkstyle-report:0.3.0
