image: maven:3.8-jdk-17  # Updated to use Maven 3.8 with OpenJDK 17

pipelines:
  default:
    - parallel:
        - step:
            name: Verify
            script:
              - mvn clean install -B  # Runs the build with Maven
            after-script:
              # Collect checkstyle results, if any, and convert to Bitbucket Code Insights.
              - pipe: atlassian/checkstyle-report:0.3.0
