image: openjdk:17  # Use OpenJDK 17 base image

pipelines:
  default:
    - parallel:
        - step:
            name: Verify
            script:
              # Install Maven manually
              - apt-get update && apt-get install -y maven
              # Run the build
              - mvn clean install -B
            after-script:
              # Collect checkstyle results, if any, and convert to Bitbucket Code Insights.
              - pipe: atlassian/checkstyle-report:0.3.0
